python_dependencies/flask/routes.py
from flask import Blueprint, render_template, redirect, send_from_directory, url_for, Flask
from flask_login import login_user
from loginform import LoginForm  
from user import User, userdb, bcrypt
from registerform import RegisterForm
from flask_wtf import CSRFProtect


app = Flask(__name__)
routes = Blueprint('routes', __name__)
routes.static_folder = '/static'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
app.config['SECRET_KEY'] = 'secret_key'
userdb.init_app(app)
csrf = CSRFProtect(app)



@routes.route("/")
def home():
    return render_template('home.html')


@routes.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    user = User()
    if user.validate_existent_user(form):
        return render_template('dashboard.html')
    return render_template('login.html', form = form)

@routes.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.register_user():
        return render_template('login.html', form = form)
    return render_template('register.html', form=form, errors=form.errors)


@routes.route("/logout")
def logout():
    form = LoginForm()
    return render_template('login.html', form = form)

@routes.route("/dashboard")
def dashboard():
    return render_template('dashboard.html')

@routes.route('/static/<path:filename>')
def serve_css(filename):
    return send_from_directory('static/css', filename)


#static\images\favicon.ico

python_dependencies/flask/templates/dashboard.html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{url_for('static', filename='images/favicon.svg')}}">
    <title>Dashboard</title>
</head>

<body>
    <h1>Hello you are logged in.</h1>
    <a href="{{url_for('routes.logout')}}">Press here to logout</a>
</body>

</html>

python_dependencies/flask/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{url_for('static', filename='images/favicon.svg')}}">
    <title>Home</title>
</head>

<body>
    <h1>Login Authentication System in Flask.</h1>
    <a href="{{ url_for('routes.login') }}">Login Page</a><br>
    <a href="{{ url_for('routes.register') }}">Register Page</a><br>

</body>

</html>

python_dependencies/flask/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{url_for('static', filename='images/favicon.svg')}}">
    <title>Login</title>
</head>

<body>
    <h1>Login Page</h1>

    <form method="POST" action="">
        {{ form.hidden_tag()}}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}
    </form>

    <a href="{{ url_for('routes.register') }}">Don't have an account? Sign Up</a>
</body>

</html>

python_dependencies/flask/templates/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - CSS-Only Floating Labels</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
  <link rel="icon" href="{{url_for('static', filename='images/favicon.svg')}}">


</head>
<body>
<!-- partial:index.partial.html -->
<body>
    </div>
    <form action="{{ url_for('routes.register') }}" method="POST" class="form">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.username.label(class="form__label") }}
        {{ form.username(class="form__input", id="username") }}
        {% for error in form.username.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form__label") }}
        {{ form.password(class="form__input", id="password") }}
        {% for error in form.password.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form__label") }}
        {{ form.email(class="form__input", id="email") }}
        {% for error in form.email.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.birthday.label(class="form__label") }}
        {{ form.birthday(class="form__input", id="birthday") }}
        {% for error in form.birthday.errors %}
          <span class="error">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.submit(class="form__input", id="submit") }}
      </div>
      <div class="a_text">
        <a href="{{ url_for('routes.login') }}">Have an account? Login here</a><br>
        <a href="{{ url_for('routes.home') }}">Main Page</a><br>
        </div>
    </form>

</body>
</html>